### PR TITLE
Add solo stakers from Allnodes

### PR DESCRIPTION
**Pull request by dozer-eth**
It seems like the classification model has incorrectly missed my solo stakers on Allnodes (for which I manage the seed/withdrawal credentials and don't pool/share any rewards).  Talking with Allnodes in their discord, they are also a Lido node operator which may be the source of confusion (beaconcha.in also erroneously seems to label 4/5 of them as "Pool: Coinbase").

I'm only including my nodes addresses, but the misclassification likely applies to all solo stakers on Allnodes.

https://beaconcha.in/validator/172818
https://beaconcha.in/validator/179612
https://beaconcha.in/validator/184157
https://beaconcha.in/validator/189991
https://beaconcha.in/validator/190160

### CODE REVIEW

**Comment by bulrathiking** [comment]
I had a similar experience with a validator at https://beaconcha.in/validator/70028. I have control over the withdraw keys, although not allnodes. Essentially, I pay for the expenses for the computing power. Allnodes functions similarly to AWS, offering support not only on the infrastructure side but also on the software and UI aspects. However, in case of any misconduct on their part, I have the ability to promptly withdraw all funds, migrate to a different platform, and they would have no recourse. This setup is essentially the same as solo staking as it helps to decentralize the network.

**Comment by jagmot** [comment]
If I can assist in any way, please let me know. I am part of the Allnodes.com team.

**Comment by ariskk** [comment]
Hi all, the Allnodes validators won't be part of the list, as it aims to capture uncorrelated solo stakers running their own infra. We can provide a separate list with non-institutional/non-LST Allnodes depositors and people can choose to use this list or not depending on the use case they want to power.

**Comment by bulrathiking** [comment]
> Hi all, the Allnodes validators won't be part of the list, as it aims to capture uncorrelated solo stakers running their own infra. We can provide a separate list with non-institutional/non-LST Allnodes depositors and people can choose to use this list or not depending on the use case they want to power.

when you say uncorrelated solo running their own infra, you mean that all the folks using aws are not included? because they are still correlated in the sense that a decision by amazon can affect all of them. allnodes is effectively the same, but much more crypto native and not a big corpo. if anything, its an improvement

**Comment by jagmot** [comment]
How does a solo staker who is on AWS or another provider control their infrastructure?

I think another list would be helpful to differentiate users who control their wallets and are 100% non-custodial. 

I would note that on August 27th, 2021 when the geth bug hurt consensus on the blockchain, Allnodes was using minority clients (Besu/Teku), which helped the ETH blockchain during that time. We also recently switched back to using Besu/Teku to help reduce centralization of validators using Geth. I hope this is recognized by Rated-Network in a future list and appreciated by others who might use the list in the future.

**Comment by ariskk** [comment]
If I control the AWS account that runs the validator, I can adjust resources, check logs, set up a failover in another region, monitor for issues etc. If I stake with a staking provider, I can't do any of that, I am at the mercy of the provider. 

There is nothing wrong in using a staking provider; in fact Allnodes has a very long history of exceptional performance and is an excellent choice. It's just that the definition of "solo staker" as defined in the original [research post](https://blog.rated.network/blog/solo-stakers) we wrote last year does not include validators who use a staking provider.

As I have mentioned before, we are merely providing a list and it is up to downstream adopters to choose how to use the list. Some adopters are happy with our definition, others might want to create their own definition. We are happy to assist, but at the end of the day it's downstream application that controls the actual implementation (and in this case it's Starkware).

**Pull request closed without merging**
